name = "toprekr-images-server"
compatibility_date = "2024-02-08"

# D1 Database Binding
[[d1_databases]]
binding = "DB" # Available in your Worker via env.DB
database_name = "toprekr-d1"
database_id = "b0dfcc55-3bae-4e2b-9d00-0b88de1b56bb"

# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET" # Available in your Worker via env.BUCKET
bucket_name = "toprekr-images"

# Pages Configuration (for Hono on Pages)
[pages_build_config]
build_command = "npm run deploy"
destination_dir = "public"
